---
title: "LightGBM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 개요 
- gbm 계열의 알고리즘이 발전하면서 `Kaggle` 대회에서 좋은 성과를 거두고 있다. 
- 대표적인 GBM 머신러닝 알고리즘 계열인 `LightGBM`을 설치해본다. 

### why LightGBM?
- LightGBM은 최근 들어 각 기업에서도 실제 서비스에 응용하기 위한 머신러닝 알고리즘으로 채택하기 시작했다. 
  + 사례: [데이터분석가로서 업무 과정과 경험, 배움을 공유합니다, 3.1 장 참조](https://woowabros.github.io/woowabros/2020/07/01/how_data_analyst_works.html)
- 가장 큰 특징 중 하나는 기존 연산속도가 길었던 GBM 계열의 다른 알고리즘보다 빠르다는 장점이 있다. 
- 자세한 내용은 공식 문서를 참조한다. 
  + [Welcome to LightGBM’s documentation!](https://lightgbm.readthedocs.io/en/latest/)
  
## I. 설치가이드
- 설치가이드는 R API 문서를 통해 확인한다. 
- 국내 대다수의 유저가 `Windows + RStudio` 인 것을 감안하여 설치 프로세스를 진행하도록 한다. 
  + 공식문서에 잘 나와 있지만, 각자의 OS 환경이 다 다르기 때문에 필자의 접근 방법만 참고하였으면 좋겠다. 
- [설치가이드 공식 문서](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html)에는 크게 3가지 버전이 있다. 
  + With GUI: visual studio에서 진행한다. 
  + From Command Line: git, CMake, VS Build Tools가 필요하다. 
  + MinGW-w64: git, Cmake, MinGW-w64 버전이 필요하다.
  + 이 중에서 필자는 `From Command Line` 버전으로 진행하였다. 
  
### (1) From Command Line
- 깃설치: https://git-scm.com/download/win 
- `CMake`설치: [CMake](https://cmake.org/) (3.18.1 or higher) 버전 설치가 필요하다. 
- [VS Build Tools](https://visualstudio.microsoft.com/downloads/) 설치를 진행한다. 
  + 만약 기존에 `Visual Studio` IDE가 존재하면 설치팔 필요는 없다. 
- 깃설치는 간단하기 때문에 본 포스트는 생략한다. 

### (2) CMake
- `CMake` 설치는 다운로드 페이지에서 진행한다. 
  + [다운로드 페이지](https://cmake.org/download/)
  + 이 때, `cmake-3.18.1-win64-x64.msi` 파일을 찾아서 설치하는 것을 권한다.
  + 이 때, 중간에 